name: Publish to GitHub Pages
on:
  push:
    branches: 
      - main
      - nolinks

jobs:
  build:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Antora
        run: npm ci

      - name: Generate Site
        run: |
            mkdir -p public/$GITHUB_REF_NAME
            npx antora antora-playbook.yml --to-dir public/$GITHUB_REF_NAME
            if [ "$GITHUB_REF_NAME" = "main" ]; then
              mv public/$GITHUB_REF_NAME/* public
            fi

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
